version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.localhost
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "80:80"
      - "8822:22"
    volumes:
      - ./gitlab/config/gitlab:/etc/gitlab
      - ./gitlab/data/gitlab:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
    networks:
      default:
        aliases:
          - gitlab.localhost.com

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./gitlab/config/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
